# Generated by Django 4.2 on 2023-06-15 19:54

from django.db import migrations, models
import playlists.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioModel',
            fields=[
                ('audio_title', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('audio_file', models.FileField(upload_to=playlists.models.play_audio_directories)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistModel',
            fields=[
                ('playlist_title', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('played_audios', models.ManyToManyField(to='playlists.audiomodel')),
            ],
        ),
    ]
