# Generated by Django 4.2 on 2023-06-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoredmodel',
            name='recorded_day',
            field=models.IntegerField(default=0),
        ),
    ]
