# Generated by Django 4.1.7 on 2023-04-24 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import file_processing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('descr', models.CharField(max_length=250)),
                ('audio_file', models.FileField(upload_to=file_processing.models.upload_audio_directory_to)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
