# Generated by Django 4.2 on 2023-06-15 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file_processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomodel',
            name='RTB',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiomodel',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audiomodel',
            name='created',
            field=models.CharField(default='2023-06-15', max_length=300),
        ),
    ]
