# Generated by Django 4.2 on 2023-05-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomodel',
            name='created',
            field=models.CharField(default='2023-05-16', max_length=300),
        ),
    ]
