# Generated by Django 4.2 on 2023-06-11 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_processing', '0002_alter_audiomodel_created_recoredmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecoredModel',
        ),
    ]
