# Generated by Django 4.2 on 2023-06-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.CharField(db_column='userRole', max_length=20, unique=True)),
                ('username', models.CharField(db_column='username', max_length=20, unique=True)),
                ('password', models.CharField(db_column='userPassword', max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_entity',
            },
        ),
    ]
